#!/usr/bin/env bash
set -eou pipefail

SSH_KEY_DIR="$HOME/.ssh/keys"

TEMPDIR="$(mktemp -d)"

for key_path in $(gopass list --flat ssh); do
    key="$(basename "$key_path")"
    keyfile="$TEMPDIR/$key.key"

    echo -e "Writing key [ \e[32m$key\e[0m ]"

    gopass show "ssh/$key" > "$keyfile"
    chmod 0600 "$keyfile"

    ssh-keygen -y -f "$keyfile" > "$keyfile.pub"
done

mkdir -p "$SSH_KEY_DIR"
rsync -a --del "$TEMPDIR/" "$SSH_KEY_DIR"
