language: python
python:
  - "3.5"
addons:
  apt:
    sources:
    - sourceline: 'ppa:neovim-ppa/unstable'
    packages:
    - build-essential
    - neovim
    - git
    - curl

before_install:
- export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
- curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
- cd zsh-5.0.7
- ./configure --prefix=$LOCAL
- make
- make install
- cd -
- export PATH="$LOCAL/bin:$PATH"
- mkdir -p ~/.config/nvim

script:
- export DOTFILES_DIR=/home/travis/build/r0bobo/dotfiles
- echo $ZPLUG_HOME
- echo $VIMLPUG_HOME
- echo $ZSH
- git clone https://github.com/zplug/zplug $ZPLUG_HOME
- git clone --depth=1 https://github.com/robbyrussel/oh-my-zsh.git $OH_MY_ZSH
- curl -fLo $VIMPLUG_HOME --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- $DOTFILES_DIR/scripts/setup-dotfiles 
- ls -A ~
