language: python
python:
    - "3.5"
addons:
  apt:
    sources:
        - sourceline: 'ppa:neovim-ppa/unstable'
        - sourceline: 'ppa:duggan/bats'
    packages:
        - neovim
        - bats

before_install:
    - export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
    - curl -L http://downloads.sourceforge.net/zsh/zsh-5.3.1.tar.gz | tar zx
    - cd zsh-5.3.1
    - ./configure --prefix=$LOCAL
    - make
    - make install
    - cd -
    - export PATH="$LOCAL/bin:$PATH"


script:
    - cd /home/travis/build/r0bobo/dotfiles
    - make test

