language: bash
python:
    - "3.5"
addons:
  apt:
    sources:
        - sourceline: 'ppa:neovim-ppa/unstable'
        - sourceline: 'ppa:duggan/bats'
    packages:
        - neovim
        - bats

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y zsh

script:
    - cd /home/travis/build/r0bobo/dotfiles
    - make test

