#!/usr/bin/env zsh

export EDITOR=editor

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# ZSH
ZSH_COMPDIR="$XDG_DATA_HOME/zsh/completions"
ZSH_CACHEDIR="$XDG_CACHE_HOME/zsh/cache"
mkdir -p "$ZSH_CACHEDIR" "$ZSH_COMPDIR"

# Path
typeset -U path # Avoid duplicate entries in PATH
path+=$HOME/.local/bin
path+=$HOME/.cargo/bin
path+=$HOME/.npm/bin
path+=$HOME/go/bin
path+=$HOME/.emacs.d/bin
path+=$HOME/.cargo/bin
path+=${KREW_ROOT:-$HOME/.krew}/bin

fpath+="$ZSH_COMPDIR"
fpath+=/usr/share/zsh/vendor-completions

# Apps
export DOOMDIR="$HOME/.local/share/chezmoi/doom"
export LIBVIRT_DEFAULT_URI=qemu+ssh://hypervisor/system
export VAULT_ADDR=https://vault.service.todevski:8200

# Manpages
export MANPAGER='bat -lman -p'

# GPG
export GPG_TTY=$(tty)
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
	export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi
