#!/bin/bash -e

# Only run when graphical
[[ "$XDG_CURRENT_DESKTOP" == '' ]] && exit 0

sudo systemctl disable --now packagekit.service
sudo systemctl disable --now packagekit-offline-update.service
sudo systemctl mask packagekit.service
sudo systemctl mask packgekit-offline-update.service

npm -g install \
	prettier \
	stylelint

firefox-link-userjs
