#!/bin/bash -e

# Only run when graphical
[[ "$XDG_CURRENT_DESKTOP" == '' ]] && exit 0


flatpaks=(
    com.bitwarden.desktop
    com.github.tchx84.Flatseal
    com.slack.Slack
    com.spotify.Client
    org.gtk.Gtk3theme.Adapta-Eta
    app/com.nextcloud.desktopclient.nextcloud/x86_64/stable
    org.telegram.desktop
)

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install flathub "${flatpaks[@]}"
