#!/bin/bash -e


packages=(

    direnv
    emacs
    exa
    fd-find
    fzf
    kubectl
    lab
    rclone
    ripgrep
    starship
    tmpwatch
    tmux
    vim
    xclip
    zsh
    zsh-autosuggestions
    zsh-fast-syntax-highlighting

    # Golang dev
    godoctor
    golang-x-tools-gopls
    golang-x-tools-gorename
    golang-x-tools-guru

)

# Graphical packages
if [[ "$XDG_CURRENT_DESKTOP" != '' ]]; then
    packages+=(

        adapta-gtk-theme
        adobe-source-code-pro-fonts
        alacritty
        flatpak
        papirus-icon-theme

    )
fi

# RPM Fusion
sudo dnf install -y "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
sudo dnf install -y "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

# Copr repos
sudo dnf copr enable -y chmouel/tektoncd-cli
sudo dnf copr enable -y robobo/packages

sudo dnf install -y "${packages[@]}"
