#! /bin/sh

sxhkd &

bspc monitor -d term web atom IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_moncocle    true

# Mouse Actions
bspc config pointer_modifier        super
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner
bspc config click_to_focus          true
bspc config focus_follows_pointer   true

# Set Desktop Rules
bspc rule -a firefox-developer desktop='^2'
bspc rule -a Atom desktop='^3'

bspc desktop web --layout monocle # Set firefox window to monocle by default

# Autostart
$HOME/.config/polybar/launch.sh  # launch polybar
nitrogen --restore  # set wallpaper
xsetroot -cursor_name left_ptr  # set mouse pointer
compton $HOME/.config/compton/compton.conf -b
