#! /bin/sh

sxhkd &

bspc monitor -d term web atom IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_moncocle true
bspc config click_to_focus       true

bspc rule -a Firefox Developer desktop='^2'
bspc rule -a Atom desktop='^3'
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Launch Polybar
$HOME/.config/polybar/launch.sh

# Set wallpaper
nitrogen --restore
