add_newline = true
follow_symlinks = false

[aws]
disabled= true
displayed_items = "all"

[aws.region_aliases]
eu-central-1 = "fra"

[gcloud]
disabled = true

[kubernetes]
disabled = true


[terraform]
disabled = true
