#!/data/data/com.termux/files/usr/bin/bash

cp create_symlinks.sh create_symlinks.sh.bak
cp create_symlinks.py create_symlinks.py.bak

termux-fix-shebang create_symlinks.sh create_symlinks.py

./create_symlinks.sh

rm create_symlinks.sh create_symlinks.py

mv create_symlinks.sh.bak create_symlinks.sh
mv create_symlinks.py.bak create_symlinks.py
