#!/usr/bin/env sh

# TODO: Create a better

# Set paths
export DOTFILES_DIR=${DOTFILES_DIR-~/dotfiles}
$DOTFILES_DIR/zsh/paths.sh

$DOTFILES_DIR/scripts/create_symlinks.py $DOTFILES_DIR $DOTFILES_DIR/dotfiles.conf

echo "Test"
echo $ZPLUG_HOME
echo $VIMLPUG_HOME
echo $ZSH

# Download modules
if [ -d !$ZPLUG_HOME ]; then
        git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi
if [ -d !$VIMLPUG_HOME ]; then
        curl -fLo $VIMPLUG_HOME --create-dirs \
                https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
if [ -d !$ZSH ]; then
        git clone --depth=1 https://github.com/robbyrussel/oh-my-zsh.git $OH_MY_ZSH
fi

# Run and update vim-plug
# nvim -c "PlugUpgrade | PlugInstall | PlugUpdate | PlugClean | q | q"

# TODO: add zplug update/install/clean/etc as well

