#!/usr/bin/env zsh

# Set paths
: ${DOTFILES_DIR:=~/dotfiles}
source $DOTFILES_DIR/zsh/paths.sh

# Run python script to setup symlinks
$DOTFILES_DIR/scripts/create_symlinks.py $DOTFILES_DIR $DOTFILES_DIR/dotfiles.conf

# Download modules
if [ ! -d "$ZPLUG_HOME" ]; then
        echo "Installing zplug..."
        git clone https://github.com/zplug/zplug $ZPLUG_HOME
else
        echo "zplug already installed."
fi
if [ ! -d "$VIMLPUG_HOME" ]; then
        echo "Installing vim-plug..."
        curl -fLo $VIMPLUG_HOME --create-dirs \
                https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
        echo "vim-plug already installed."
fi

# Source zsh-config
source $DOTFILES_DIR/zsh/init.zsh

# Run and update zplug
zplug clear
zplug list
zplug check || zplug install
zplug clean --force
zplug load --verbose

# Run and update vim-plug
timeout 300s nvim -V9myVim.log -c "PlugStatus | qa"
# nvim -c "PlugUpgrade | PlugInstall | PlugUpdate | PlugClean! | q | q"

