#!/data/data/com.termux/files/usr/bin/bash

cp setup-dotfiles setup-dotfiles.bak
cp create_symlinks.py create_symlinks.py.bak

termux-fix-shebang setup-dotfiles create_symlinks.py

./setup-dotfiles

rm setup-dotfiles create_symlinks.py

mv setup-dotfiles.bak setup-dotfiles
mv create_symlinks.py.bak create_symlinks.py
