#!/usr/bin/env zsh

# TODO: Create a better

# Set paths
: ${DOTFILES_DIR:=~/dotfiles}
: ${ZSH:=~/.oh-my-zsh}
: ${ZPLUG_HOME:=~/.zplug}
: ${VIMPLUG_HOME:=~/.local/share/nvim/site/autoload/plug.vim}

$DOTFILES_DIR/scripts/create_symlinks.py $DOTFILES_DIR $DOTFILES_DIR/dotfiles.conf

echo "Env variables:"
echo $ZSH
echo $ZPLUG_HOME
echo $VIMPLUG_HOME

# Download modules
if [ ! -d "$ZPLUG_HOME" ]; then
        echo "Installing zplug..."
        git clone https://github.com/zplug/zplug $ZPLUG_HOME
else
        echo "zplug already installed."
fi
if [ ! -d "$VIMLPUG_HOME" ]; then
        echo "Installing vim-plug..."
        curl -fLo $VIMPLUG_HOME --create-dirs \
                https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
        echo "vim-plug already installed."
fi
if [ ! -d "$ZSH" ]; then
        echo "Installing oh-my-zsh..."
        git clone https://github.com/robbyrussell/oh-my-zsh $ZSH
else
        echo "oh-my-zsh already installed."
fi

# Source zsh-config
echo "ZSH init"
source $DOTFILES_DIR/zsh/init.zsh

# Run and update vim-plug
# nvim -c "PlugUpgrade | PlugInstall | PlugUpdate | PlugClean[!] | q | q"

# TODO: add zplug update/install/clean/etc as well
