# Powerlevel9k Settings

export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir vcs)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status virtualenv time)
export POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
export POWERLEVEL9K_SHORTEN_DELIMITER=""
# export POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"


# Colors
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='blue'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black'
