# Zsh init script

# Setup paths
export DOTFILES=${DOTFILES-~/.dotfiles}
export ZPLUG_HOME=${ZPLUG_HOME-~/.zplug}
export VIMPLUG_HOME=${VIMPLUG_HOME-~/.local/share/nvim/site/autoload/plug.vim}
export PATH=$HOME/.local/bin:$PATH

# Start tmux
if command -v tmux>/dev/null; then
  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi

# General zsh settings

export EDITOR='nvim'
export DEFAULT_USER=`whoami`
export USER=`whoami`


# History
export HISTFILE=~/.zsh_history
export HISTSIZE=1000
export SAVEHIST=1000

setopt append_history
setopt hist_ignore_dups
setopt hist_expire_dups_first
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history


# Completion
setopt always_to_end
setopt auto_menu
setopt complete_in_word

zstyle ':completion:*' menu select
zstyle ':completion:*:default'  list-colors ${(s.:.)LS_COLORS}
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'


autoload -Uz compinit promptinit run-help
compinit
promptinit


# setopt correct
# setopt correctall
setopt auto_cd
setopt auto_pushd


# Fix right prompt offset
ZLE_RPROMPT_INDENT=0


export KEYTIMEOUT=1
# Zsh aliases

alias zshreload="source ~/.zshrc"
alias promptreload="source $DOTFILES/zsh/prompt.zsh"

# Directory
alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lAh --color=auto'

if hash termux-fix-shebang 2>/dev/null;then
    alias upgrade_dotfiles="sh $DOTFILES/scripts/setup-dotfiles-termux"
else
    alias upgrade_dotfiles="zsh $DOTFILES/scripts/setup-dotfiles"
fi

alias grep='grep --color=auto'  # Color grep
# Zplug plugin setup

source $ZPLUG_HOME/init.zsh

zplug "zsh-users/zsh-autosuggestions"
zplug "zdharma/fast-syntax-highlighting"
zplug "jreese/zsh-titles"
zplug "srijanshetty/zsh-suffix-alias"

# Themes

zplug "mafredri/zsh-async", from:github
# zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
# zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
zplug "dfurnes/purer"

zplug load

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
